body:
  - type: markdown
    attributes:
      value: |
        > **Note**: For discussions not related to Vercel CLI or Runtimes, please visit the [Vercel Community](https://github.com/orgs/vercel/discussions/categories/ideas)
  - type: textarea
    attributes:
      label: Idea
    validations:
      required: true
